# Generated by Django 5.1.1 on 2024-10-10 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("videodownloader", "0002_alter_video_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="video",
            name="uploaded_at",
        ),
    ]
