# Generated by Django 5.1.1 on 2024-10-10 08:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videodownloader", "0003_remove_video_uploaded_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
