# Generated by Django 5.1.1 on 2024-10-26 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videodownloader", "0004_video_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="uploader",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
