# Generated by Django 5.1.2 on 2024-12-08 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_phone_number_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='nom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
